<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mode_app_description'] = 'Приложение "Режим" обеспечивает низкоуровневую систему драйвера для основного/подчиненного режима.';
$lang['mode_app_name'] = 'Менеджер режима';
$lang['mode_master'] = 'Мастер';
$lang['mode_mode'] = 'Режим';
$lang['mode_mode_is_invalid'] = 'Режим является недействительным.';
$lang['mode_slave'] = 'Подчиненный';
$lang['mode_standalone'] = 'Автономный';
$lang['mode_system_mode_driver_not_set'] = 'Системный драйвер режима не установлена.';
