<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mode_app_description'] = 'The Mode app provides a low-level driver system for master/slave mode.';
$lang['mode_app_name'] = 'Mode Manager';
$lang['mode_master'] = 'Master';
$lang['mode_mode'] = 'Mode';
$lang['mode_mode_is_invalid'] = 'Mode is invalid.';
$lang['mode_slave'] = 'Slave';
$lang['mode_standalone'] = 'Standalone';
$lang['mode_system_mode_driver_not_set'] = 'System mode driver is not set.';
