<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mode_app_description'] = 'Aplikacja trybu pracy dostarcza niskopoziomowy sterownik systemu dla tryby samodzielnego i podrzędnego.';
$lang['mode_app_name'] = 'Menedżer trybu pracy';
$lang['mode_master'] = 'Nadrzędny';
$lang['mode_mode'] = 'Tryb pracy';
$lang['mode_mode_is_invalid'] = 'Tryb pracy jest nieprawidłowy.';
$lang['mode_slave'] = 'Podrzędny';
$lang['mode_standalone'] = 'Samodzielny';
$lang['mode_system_mode_driver_not_set'] = 'Sterownik trybu pracy systemu nie został ustawiony.';
